---

- hosts: all
  user: root
  sudo: True
  gather_facts: False
  connection: local
  vars_files: 
    - vars.yml
  vars_prompt:
    - name: "mailer_password"
      prompt: "Enter password for gmail mail user"
      private: yes

  roles:
    - common
    - blog
