---

- hosts: all
  user: root
  sudo: True
  gather_facts: False
  connection: local
  vars_files: 
    - vars.yml
  vars_prompt:
    mailer_password: "Enter password for mailer_user"

  roles:
    - common
    - blog
