- name: Install python-pycurl
  apt: pkg=python-pycurl state=present 

- name: Add nginx PPA repository
  apt_repository: repo='ppa:nginx/stable' update_cache=yes

- name: Install nginx package
  apt: pkg=nginx-full state=present 

- name: Disable default nginx virtualhost
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Enable nginx on boot
  service: name=nginx enabled=yes